export const useAr = () => useState(() => {
  return{
    "page":"صفحة",
    "dashboard":"لوحة التحكم",
    "accounts":"حسابات",
    "block":"بلوك",
    "blocks":"بلوكات",
    "image":"صورة",
    "new-block":"بلوك جديد",
    "courses":"دورات",
    "login-failed":"عذرًا، حدث خطأ أثناء محاولة تسجيل الدخول. يرجى التأكد من صحة الإيميل وكلمة المرور والمحاولة مرة أخرى. إذا استمرت المشكلة، يُرجى التواصل مع الدعم الفني.",
    "order":"الترتيب",
    "isActive":"فعال",
    "type":"النوع",
    "english":"انكليزي",
    "arabic":"عربي",
    "icon":"الأيقونة",
    "content":"المحتوى",
    "add-description":"إضافة وصف",
    "add-field":"إضافة حقل",
    "page-size":"العدد بالصفحة",
    "add":"إضافة",
    "logged-in-successfully":"تم تسجيل الدخول بنجاح.",
    "valid-email":"يرجى إدخال ايميل حقيقي.",
    "required-field":"الحقل مطلوب",
    "sent-successfully":"تم إرسال المعلومات بنجاح",
    "hire-date":"تاريخ التعيين",
    "job-title":"المسمى الوظيفي",
    "manager-details":"تفاصيل الإداري",
    "coach-details":"تفاصيل المدرب",
    "player-details":"تفاصيل لاعب",
    "player-name":"اسم اللاعب",
    "back":"العودة",
    "Finished":"انتهت",
    "Not Yet":"لم تلعب",
    "group":"المجموعة",
    "match-num":"رقم المباراة",
    "coaches":"المدربون",
    "managers":"الإداريون",
    "click-to-download":"انقر هنا للتحميل",
    "drop-the-files-here":"أسقط الملفات هنا",
    "approve":"تأكيد",
    "approve-termination":"هل تريد بالفعل إنهاء عقد: ",
    "contract-termination":"إنهاء عقد",
    "edit-and-renewal":"تعديل وتجديد",
    "runs":"الأشواط",
    "result":"النتيجة",
    "referee":"الحكم",
    "playground":"الملعب",
    "matches":"المباريات",
    "team":"الفريق",
    "position":"المركز",
    "remain":"متبقي",
    "loss":"خسر",
    "won":"فاز",
    "played":"لعب",
    "upcoming-matches":"المباريات القادمة",
    "matches-management":"إدارة المباريات",
    "arrangement":"الترتيب",
    "winner":"الفــــائز",
    "role":"الدور",
    "season":"الموسم",
    "players":"اللاعبون",
    "foundation-year":"السنة التأسيسية",
    "report":"تقرير",
    "date":"التاريخ",
    "Reject":"رفض",
    "Accept":"قبول",
    "Renew Managers":"تجديد إداري",
    "New Managers":"إداري جديد",
    "Renew Coach":"تجديد مدرب",
    "New Coach":"مدرب جديد",
    "Renew Player":"تجديد لاعب",
    "New Player":"لاعب جديد",
    "Matches Management":"إدارة المباريات",
    "Order Management":"إدارة الطلبات",
    "Coaches and Manager Management":"إدارة المدربين والإداريين",
    "Player Management":"إدارة اللاعبين",
    "Team management":"إدارة الفرق",
    "logo":"الشعار",
    "certificates":"الشهادات المعتمدة",
    "notes":"ملاحظات",
    "no-data":"لايوجد بيانات",
    "add-attachment":"إضافة مرفق",
    "attachment-name":"اسم المرفق",
    "attachment":"مرفق",
    "guardian-acknowledgment-photo":"صورة اقرار ولي الأمر",
    "player-photo":"صورة اللاعب",
    "coach-photo":"صورة المدرب",
    "manager-photo":"صورة الإداري",
    "member-form-photo": "صورة استمارة عضو جديد",
    "manager-form-photo":"صورة استمارة إداري جديد",
    "coach-form-photo":"صورة استمارة مدرب جديد",
    "player-form-photo":"صورة استمارة لاعب جديد",
    "passport-photo":"صورة جواز السفر",
    "ID-photo":"صورة الهوية",
    "player-number":"رقم اللاعب",
    "international-classification":"التصنيف العالمي",
    "national-team":"المنتخب الوطني",
    "local-classification":"التصنيف المحلي",
    "passport-number":"رقم جواز السفر",
    "ID-number":"رقم الهوية",
    "registration-number":"رقم القيد",
    "registration":"التسجيل",
    "age-category":"الفئة العمرية",
    "Federation-Championships-And-Events":"بطولات وأحداث الاتحاد",
    "Matchs":"مباريات",
    "daily-reservation-fee":"رسم حجز يوم",
    "Worker":"عامل",
    "Affiliate":"منتسب",
    "show-more":"عرض المزيد",
    "search-results":"نتائج البحث",
    "no-matching-results":"لا يوجد نتائج مطابقة",
    "identification-photo":"صورة للهوية",
    "salary-receipt":"صورة وصل استيلام الراتب",
    "price-after-discount":"السعر بعد الحسم",
    "You are a subscriber to the Solidarity Fund":"أنت مشترك بصندوق التكافل.",
    "Your request has been sent successfully.":"لقد تم إرسال طلبك بنجاح.",
    "new-member-fee":"رسم اشتراك عضو جديد",
    "server-error":"خطأ في الخادم، يرجى التواصل مع الإدارة لحل المشكلة!",
    "false":"لا",
    "true":"نعم",
    "active":"فعال",
    "inactive":"غير فعال",
    "Letter-Of-Commitment-From-Employer":"خطاب الالتزام من صاحب العمل",
    "last-installement-amount":"قيمة القسط الأخير",
    "installement-amount":"قيمة القسط",
    "for-expatriates":"صورة من جواز السفر مع إقامة سارية المفعول للوافدين",
    "membership-number":"رقم العضوية",
    "membership-type":"نوع العضوية",
    "mailbox":"صندوق البريد",
    "job-address":"عنوان العمل",
    "loan-id":"معرف القرض",
    "id":"المعرف",
    "date":"التاريخ",
    "new-loan":"قرض جديد",
    "current-loan":"القرض الحالي",
    "previous-loans":"قروض سابقة",
    "reservations-and-subscriptions":"الحجوزات والاشتراكات",
    "reservations":"الحجوزات",
    "subscriptions":"الاشتراكات",
    "accepted-loans":"قروض موافق عليها",
    "pending-loans":"قروض بانتظار الموافقة",
    "nothing":"لا يوجد",
    "no-installments-paid-yet":"لا أقساط مسددة حتى الآن",
    "rest":"الباقي",
    "sum-payment-amounts":"إجمالي قيمة الدفعات",
    "payment-amount":"قيمة الدفعة",
    "num":"رقم",
    "installments":"دفعات القروض",
    "loan-installment":"دفعات قرض",
    "A copy of the qualification license":"نسخة عن شهادة المؤهل العلمي",
    "job-address":"عنوان العمل",
    "job":"المهنة",
    "guest-registration":"تسجيل كزائر",
    "search-the-association":"ابحث في الجمعية",
    "what-are-you-looking-for?":"ما الذي تبحث عنه؟",
    "loan":"قرض",
    "loan-of-solidarity-fund":"قرض صندوق التكافل",
    "review-solidarity-fund-req":"لقد تم تقديم طلبك بالاشتراك بصندوق التكافل وهو في حالة التدقيق.",
    "loan-amount":"قيمة القرض بالدرهم الإماراتي",
    "solidarity-fund":"صندوق التكافل",
    "Start Date":"تاريخ البدء",
    "End Date":"تاريخ الانتهاء",
    "End Subscription":"انتهاء الاشتراك",
    "Emirate":"الإمارة",
    "Price":"السعر",
    "Discount":"حسم",
    "exhibitions":"معارض",
    "exhibition":"المعرض",
    "membership":"العضوية",
    "membership-renewal":"تجديد العضوية",
    "Renewal of membership in the Journalists Association":"تجديد العضوية في جمعية الصحفيين",
    "Subscription to the Arab Journalists Union":"إشتراك اتحاد الصحفيين العرب",
    "Subscribe to the International Union of Journalists":"اشترك في الاتحاد الدولي للصحفيين",
    "membership-status":"حالة العضوية",
    "submit-renewal":"تقديم طلب تجديد عضوية",
    "submit-membership-request":"تقديم طلب عضوية",
    "submit-solidarity-fund-subscribes":"تقديم طلب اشتراك بصندوق التكافل",
    "read-more":"اقرأ المزيد",
    "journalists-unions-and-associations":"نقابات وجمعيات الصحفيين",
    "journalists-from-the-beautiful-era":"صحفيين من العصر الجميل",
    "number-of-members":"عدد الأعضاء",
    "number-of-events":"عدد الفعاليات",
    "show-all":"عرض الكل",
    "activities":"فعاليات",
    "activity":"الفعالية",
    "refresh":"تحديث",
    "membership-registration":"تسجيل العضوية",
    "and":" و",
    "sponsors":"الرعاة",
    "sponsor":"راعي",
    "friendly-sites":"مواقع صديقة",
    "friendly-site":"موقع صديق",
    "most-view":"الأكثر مشاهدة",
    "menu":"القائمة",
    "less":"أقــل",
    "back-to-home":"العودة للصفحة الرئيسية",
    "page-not-found":"الصفحة غير موجودة",
    "could-not-find-page-msg":"تعذر العثور على الصفحة المطلوبة",
    "error-occurred-msg":"حدث خطأ",
    "appointment-date": "تاريخ الموعد",
    "appointment-time": "وقت الموعد",
    "loading":"يتم التحميل، الرجاء الانتظار",
    "wait-registration":"الرجاء الانتظار ريثما يتم التسجيل",
    "wait": "الرجاء الانتظار",
    "otheradv":"عقارات  مشابهة",
    "Payment plan":"خطة الدفع",
    "Project brochure":"كتيب العقار",
    "bathroom":"عدد الحمامات",
    "Number of rooms":"عدد الغرف ",
    "Property area":"مساحة العقار",
    "floorNumber":"رقم الطابق",
    "projectNumber":"رقم العقار",
    "realtyStatus":"حالة العقار",
    "name":"الاسم",
    "realtyValue":"سعر العقار",
    "realltyContract":"عقد العقار",
    "Building number":"رقم البناء",
    "room":"غرفة",
    "The property is not available now":"العقار ليس متاحا الآن للحجز",
    "RoomCount":"عدد الغرف",

    "Appointment Booking":"حجز موعد",
    "Reserve the Realty":"حجز العقار",
    "Real Estate":"إدارة العقارات",
    "Real-Estate": "العقارات",
    "Book a property":"حجز عقار",
    "Property Details":"تفاصيل العقار",
    "Book an Appointment":"حجز موعد",
    "About Us": "من نحن",
    "About the project": "نبذة عن المشروع",
    "Change Language": "تغيير اللغة",
    "An overview of the developing company": "نبذة عن الشركة المطورة",
    "Speech of the Chairman of the Board of Directors": "كلمة رئيس مجلس الإدارة",
    "Vision, mission and goals": "الرؤية والرسالة والأهداف",
    "Our projects": "مشاريعنا",
    "Project Name": "اسم المشروع",
    "Details about the project": "تفصيل عن المشروع ",
    "Al-Sabari Building": "بناية السعبري",
    "Al-Saabari Building Project Al-Saabari Building Project Al-Saabari Building Project Al-Saabari Building Project Al-Saabari Building Project Al-Saabari Building Project": "مشروع بناية السعبري مشروع بناية السعبري مشروع بناية السعبري مشروع بناية السعبري مشروع بناية السعبري مشروع بناية السعبري",
    "Project Detail": "تفاصيل المشروع",
    "The mosque": "المسجد",
    "Reserve the property": "حجز العقار",
    "Name": "الاسم",
    "Phone Number": "رقم الموبايل",
    "Second Phone Number": "رقم الموبال الثاني",
    "Building number (or building name)": "رقم البناية (أو اسم البناية)",
    "Apartment number": "رقم الشقة",
    "Contact Us": "الاتصال بنا",
    "Address": "العنوان",
    "job opportunities": "الوظائف الشاغرة",
    "Frequently_Asked_Questions": "الأسئلة الشائعة",
    "News": "الأخبار",
    "gallery": "ألبوم الصور",
    "photo-gallery" : "معرض الصور",
    "Welcome_To_Frequently_Asked_Questions": "مرحبًا بك في الأسئلة الشائعة",
    "Here_you_can_find_the_answers_youre_looking for": "هنا يمكنك العثور على الإجابات التي تبحث عنها",
    "Sponsers": "الشركاء",
    "AL SABARI RESIDENCE": "بناء السعبري",
    "This future project have several nearby landmarks such as Kent College Dubai, Kent Nursery Dubai, Champions Karate Academy, Meydan South Villas, Zen Star Badminton Academy, United Football Club Dubai, Meydan South Villas, LLFPM School, Nad Al Sheiba Mini Forest Trail, etc": "يضم هذا المشروع المستقبلي العديد من المعالم القريبة مثل كلية كينت دبي، وحضانة كينت دبي، وأكاديمية أبطال الكاراتيه، وفيلات ميدان الجنوبية، وأكاديمية زين ستار لتنس الريشة، ونادي يونايتد لكرة القدم في دبي، وفيلات ميدان الجنوبية، ومدرسة إل إل إف بي إم، ومسار غابة ند الشيبة الصغيرة، إلخ. .",
    "Public facilities": "المرافق العامة",
    "swimming pool": "مسبح",
    "supermarket": "سوبر ماركت",
    "Tennis Court": "ملعب تنس",
    "Incubation": "حضانة",
    "Open yard": "ساحة مفتوحة",
    "Dressing Room": "غرفة ملابس",
    "Basketball": "كرة سلة",
    "Appointment Time": "وقت الموعد",
    "Mosque": "مسجد",
    "Running track": "مضمار جري",
    "Visitors' position": "موقف الزوار",
    "Download Bruchures": "تحميل الكتيبات",
    "The community is divided into different parcels: the west edge of District 11, adjacent to Al Ain Road": "ينقسم المجمّع إلى قطاعات مختلفة: الحافة الغربية للمنطقة 11، المجاورة لطريق العين",
    "Parcels C, D & L, are planned as medium density (G+5 apartments), located between Al Ain Road and the low density parcels (villas) to the east": "تم تخطيط القطاعات C وD وL  على أنها متوسطة الكثافة ( أرضي + 5 شقق )، وتقع بين طريق العين و القطاعات منخفضة الكثافة (الفلل) شرقاً",
    "explore": "استكشف",
    "Detail": "التفاصيل",
    "Floor plans": "المخططات",
    "Search": "بحث",
    "clearfilter": "مسح الفلترة",
    "Small space": "المساحة الصغرى",
    "Great area": "المساحة العظمى",
    "pricelow": "السعر الأدنى",
    "pricehigh": "السعر الأعلى",
    "realtyType": "نوع العقار",
    "Building": "البناء",
    "Register your interest now": "سجل اهتمامك الآن",
    "Can a broker help you?": "هل يساعدك وسيط؟",
    //==============================
    "lang":"english",
    "best-seller":"الأكثر مبيعاً",
    "conform":"تأكيد",
    //==============================
    "Company-Arabic-Name":"اسم الشركة بالعربي",
    "Company-English-Name":"اسم الشركة بالانكليزي",
    "Arabic-Responsible-Person-Name":"اسم الشخص المسؤول بالعربي",
    "English-Responsible-Person-Name":"اسم الشخص المسؤول بالانكليزي",
    "Responsible-Person-Mobile":"رقم هاتف الشخص المسؤول",
    "Pending":"بانتظار الموافقة",
    "influencer":"المؤثر الاجتماعي",
    "influencers":"المؤثرين الاجتماعيين",
    "events":"الأحداث",
    "book-online": "احجز أونلاين",
    "search":"بحث",
    "choose-a-platform":"اختر منصة تواصل",
    "subscribe-to-our-mail":"اشترك بقائمتنا البريدية",
    "book-now":"احجز الآن",
    "client":"زبون",
    "followers":"المتابعين",
    "photos":"الصور",
    "packages":"باقات",
    "my-packages":"باقاتي",
    "our-packages":"باقاتنا",
    "similar-packages":"باقات مشابهة",
    "similar-products":"منتجات مشابهة",
    "empty":"فارغ",
    "new-package":"باقة جديدة",
    "package-name-in-arabic":"اسم الباقة بالعربي",
    "package-name-in-english":"اسم الباقة بالانكليزي",
    "description-in-arabic":"الوصف بالعربي",
    "description-in-english":"الوصف بالانكليزي",
    "package-type":"نوع الباقة",
    "add-new-package":"إضافة باقة جديدة",
    "edit":"تعديل",
    "delete":"حذف",
    "social-media-url": "رابط الحساب",
    "social-media-type": "نوع وسيلة التواصل الاجتماعي",
    "add-new-social-media":"إضافة وسيلة تواصل جديدة",
    "bio":"نبذة مختصرة",
    "additional-info":"معلومات إضافية",
    "influencers-packages":"باقات المؤثرين الاجتماعيين",
    "website-packages":"باقات الموقع",
    "website-services":"خدمات الموقع",
    "our-services":"خدماتنا",
    "your-order":"طلباتك",
    "cancel":"إلغاء",
    "package-name":"اسم الباقة",
    "news":"الأخبار",
    "show-profile":"عرض الملف الشخصي",
    "show-package":"عرض الباقة",
    "Photo-album":"ألبوم الصور",
    "Video-album":"ألبوم الفيديو",
    "old-price":"السعر القديم",
    "new-price":"السعر الجديد",
    "months":"الأشهر",
    "about-me":"لمحة عني",
    "note1":"أضف بعض المعلومات عنك",
    "note2":"لا يوجد معلومات لعرضها",
    "newsall":"كل الأخبار",
    "print":"طباعة",
    //============
    "follow-us":"تابعنا",
    "occasions-and-holidays":"الأعياد والمناسبات",
    "On_Our_Site":"في موقعنا",
    "Log_in_to_get_all_our_services":"قم بتسجيل الدخول لتحصل على كافة خدماتنا",
    "User_Name":"اسم المستخدم",
    "Password":"كلمة المرور",
    "Log_In":"تسجيل الدخول",
    "Register Now":"سجل الآن",
    "Register":"التسجيل",
    "Individual registration":"تسجيل الأفراد",
    "Company registration":"تسجيل الشركات",
    "country":"البلد",
    "My-Profile":"حسابي",
    "city":"المدينة",
    "nameCompany":"اسم الشركة",
    "Employment":"مجال العمل",
    "nameResponsible":"اسم الشخص المسؤول",
    "candy":"حلويات",
    "gift":"هدايا",
    "flower":"زهور",
    "AED":"درهم",
    "actions":"خيارات",
    "our-latest-products":"آخر منتجاتنا",
    "latest-products":"آخر المنتجات",
    "Cart Shop":"سلة المشتريات",
    "hello": "مرحبا",
    "language": "العربية",
    "sign-up": "تسجيل جديد",
    "login": "تسجيل دخول",
    "logout": "تسجيل خروج",
    "email": "البريد الالكتروني",
    "username": "اسم المستخدم",
    "fullname" : "الأسم الكامل",
    "fullnameEn" : "الاسم الكامل بالأنكليزية",
    "fullnameAr" : "الاسم الكامل بالعربية",
    "fullnameEnc" : "اسم الشركة بالأنكليزية",
    "fullnameArc" : "اسم الشركة بالعربية",
    "fullnameInfluencer" : "اسم المؤثر الاجتماعي",
    "fullnameInfluencerAr" : "اسم المؤثر الاجتماعي بالعربي",
    "fullnameInfluencerEn" : "اسم المؤثر الاجتماعي بالانكليزي",
    "password": "كلمة المرور",
    "confirmpassword": "تأكيد كلمة المرور",
    "gender": "الجنس",
    "website":"الموقع الإلكتروني",
    "address": "العنوان",
    "englishAddress" : "العنوان بالانكليزي",
    "arabicAddress" : "العنوان بالعربي",
    "birthDate": "تاريخ الميلاد",
    "phone": "رقم الهاتف",
    "mobile": "رقم الموبايل",
    "home": "الصفحة الرئيسية",
    "profile": "الملف الشخصي",
    "editeprofile":"تعديل المعلومات",
    "my-account" : "حسابي",
    "reset-password" : "إعادة تعيين كلمة المرور",
    "Change-Password" : "تغيير كلمة المرور",
    "about-us": "حولنا",
    "contact-us" : "اتصل بنا",
    "contact" : "التواصل",
    "how-it-work" : "كيف تعمل",
    "more": "المزيد",
    "offers": "عروض",
    "special-offers": "عروض خاصة",
    "craft-your-prepaid-card": "اصنع بطاقتك المدفوعة مسبقًا",
    "craft-your-card": "اصنع بطاقتك مسبقًا",
    "faq" : "الأسئلة الشائعة",
    "what-we-do": "ما الذي نفعله",
    "privacy-policy": "سياسة الخصوصية",
    "returns-and-refunds": "الأستبدال والترجيع",
    "terms-conditions": "الشروط و الاحكام",
    "view-all": "مشاهدة الكل",
    "view-more": "مشاهدة المزيد",
    "our-products": "منتجاتنا",
    "send": "إرسال",
    "Dear Sir/Madam, I am looking for products with the following specifications:":"Dear Sir/Madam, I'm looking for products with the following specifications:",
    "type-your-name": "ادخل اسمك",
    "type-your-email": "ادخل ايميلك",
    "type-your-subject": "ادخل العنوان",
    "type-your-message": "ادخل نص الرسالة",
    "login-to-enter": "قم بالتسجيل للدخول",
    "forgot-password": "نسيت كلمة المرور",
    "select-metal" : "اختر المعدن",
    "card-number": "رقم البطاقة",
    "card-number-one": "رقم البطاقة الأولى",
    "card-number-two": "رقم البطاقة الثانية",
    "orders": "طلباتي",
    "arabicName": "الاسم العربي",
    "englishName": "الاسم الانكليزي",
    "passport-arabicName": "الاسم بالعربي حسب جواز السفر",
    "passport-englishName": "الاسم بالانكليزي حسب جواز السفر",
    "loggedInMandatory": "يجب عليك تسجيل الدخول لمتابعة العملية",
    "small": "صغيرة ( مستطيلة )",
    "large" : "كبيرة ( مربعة )",
    "next": "التالي",
    "previous": "السابق",
    "shipping-cost": "كلفة الشحن",
    "cache": "كاش",
    "online": "اونلاين",
    "order-now": "اطلب الآن",
    "with-shipping": "مع الشحن",
    "without-shipping": "من دون الشحن",
    "with-warranty": "مع التأمين",
    "without-warranty": "من دون التأمين",
    "product-information": "معلومات المنتج",
    "user-information": "معلومات المستخدم",
    "shipping-warranty": "الشحن والتأمين",
    "payment": "طرق الدفع",
    "countries" : "الدول",
    "nationality" : "الجنسية",
    "select-countries" : "اختر الدولة",
    "cities" : "المدينة",
    "card-care" : "رعاية الكرت",
    "card-price" : "تكلفة الكارد",
    "care-price" : "تكلفة الرعاية",
    "our-designer-price" : "تكلفة اختيار مصممنا",
    "total-card-price" : "تكلفة الكارد الكلي",
    "select-cities" : "اختر المدينة",
    "shipping-price" : "تكلفة الشحن",
    "warranty-price" : "تكلفة التأمين",
    "total-price" : "المجموع الكلي",
    "final-price" : "المجموع النهائي",
    "continue-process" : "متابعة العملية",
    "continue" : "المتابعة",
    "add-to-cart": "اضافة لسلة المشتريات",
    "color-name" : "اسم اللون",
    "select-color" : "اختر اللون",
    "server-error": "خطأ بالخادم، يرجى التواصل مع الإدارة لحل المشكلة",
    "save": "حفظ",
    "no": "لا",
    "yes": "نعم",
    "text-one": "النص الاول",
    "text-two": "النص الثاني",
    "category":"الفئة",
    "Customer_Service":"خدمة الزبائن",
    "My_Cart":"سلة المشتريات",
    "Shop_By_Brands":"التسوق بالماركات",
    "Shop":"التسوق",
    "Offers":"العروض",
    "Links":"الروابط",
    "Invoices":"الفواتير",
    "Message":"الرسالة",
    "Customer Care":"رعاية العملاء",
    "empty-cart": "إفراغ سلة المشتريات",
    "product-name": "اسم المنتج",
    "amount": "الكمية",
    "quantity": "الكمية",
    "price":"السعر",
    "product-image": "صورة المنتج",
    "password-not-valid": "يجب أن تحتوي كلمة المرور على حرف كبير واحد على الأقل وحرف صغير",
    "no-data": "لايوجد بيانات لعرضها",
    "load-more": "عرض المزيد...",
    "Services & Suppliers":"الخدمات والموردين",
    "Country":"البلد",
    "Suppliers Membership":"عضوية الموردين",
    "Suppliers Registration":"تسجيل الموردين",
    "Suppliers Login":"حساب الموردين",
    "Added value Services":"خدمات القيمة المظافة",
    "Urgent Request":"طلب عاجل",
    "Request For Quotation":"طلب عروض اسعار",
    "Trading Service":"خدمات التجارة",
    "Trading Insurance":"التأمين التجاري",
    "Logistic Services":"الخدمات اللوجستية",
    "CHOOSE COUNTRY":"اختر البلد",
    "United Arab Emirates":"الإمارات العربية المتحدة",
    "Sudan":"السودان",
    "Suppliers Services":"خدمات الموردين",
    "Categories":"الفئات",
    "subcategory":"الفئة الفرعية",
    "Type":"النوع",
    "Company Sector":"قطاع الشركات",
    "Free delivery on first order":"توصيل مجاني عند أول طلبية",
    "Cach on delivery":"الدفع عند التسليم",
    "Free returns":"إعادة مجانية",
    "Limmited Offers":"عروض خاصة",
    "More":"المزيد",
    "Subscribe":"اشتراك",
    "Order":"طلب",
    "Home":"الرئيسية",
    "Shop By":"تصنيف حسب",
    "Products Details":"تفاصيل المنتج",
    "Description":"الوصف",
    "OTHER SIMILAR PRODUCTS":"منتجات مشابهة",
    "Join free":"انضم مجانا",
    "Forget Your Password":"نسيت كلمة السر",
    "Remember me":"تذكرني",
    "If you don’t have an account please":"إذا لم يكن لديك حساب ",
    "Customer":"زبون فرد",
    "Wholesale":"زبون شركة",
    "Required field":"حقول إلزامية",
    "Optional field":"حقول اختيارية",
    "fax":"الفاكس",
    "mailBox":"صندوق البريد",
    "Male":"ذكر",
    "Female":"أنثى",
    "Responsible Person Name Ar":"أسم الشخص المسؤول بالعربية",
    "Responsible Person Name En":"أسم الشخص المسؤول بالإنكليزية",
    "Responsible Person Mobile":"رقم هاتف الشخص المسؤول",
    "Please Login To Your Account Then Send":"الرجاء تسجيل الدخول لإرسال",
    "Tell suppliers what you need":"اخبر الموردين ماذا تحتاج",
    "Complete your Urgent Request":"اكمل طلبك العاجل",
    "The more specific your information, the more accurately we can match your request to the right suppliers":"كلما كانت معلوماتك أكثر تحديدًا ، زادت دقة مطابقة طلبك مع الموردين المناسبين",
    "Exporting country information":"معلومات الدولة المصدرة",
    "Importing country information":"معلومات الدولة المستوردة",
    "cityAr":"اسم المدينة بالعربية",
    "cityEn":"اسم المدينة بالإنكليزية",
    "portar":"اسم الميناء بالعربية",
    "porten":"اسم الميناء بالانكليزية",
    "Drag and drop files here, or Click to select files":"اسحب الملفات وأفلتها هنا ، أو انقر لتحديد الملفات",
    "I have read, understood and agreed to abide by Terms and Conditions Governing Urgent Request":"لقد قرأت وفهمت ووافقت على الالتزام بالشروط والأحكام التي تحكم الطلب العاجل",
    "Submit Urgent Request":"إرسال الطلب العاجل",
    "Complete your RFQ":"اكمل طلب عرض الأسعار",
    "Submit RFQ":"ارسل طلب عرض الأسعار",
    "Complaints And Suggestions":"الشكاوي والاقتراحات",
    "Urgent Requests":"الطلبات العاجلة",
    "RFQ":"طلبات عروض الأسعار",
    "Inquiries":"الاستفسارات",
    "My balance (Reward points)":"رصيدي (نقاط المكافأة)",
    "full Name":"الاسم الكامل",
    "Company Name":"اسم الشركة",
    "Responsible Person Name":"اسم الشخص المسؤول",
    "Order Number":"رقم الطلبية",
    "Order date":"تاريخ الطلبية",
    "Status":"الحالة",
    "Action":"العمليات",
    "Back":"رجوع",
    "Order Details":"تفاصيل الطلبية",
    "Payment Status":"حالة الدفع",
    "Created Date":"تاريخ الانشاء",
    "Order Tracking":"تتبع الطلبية",
    "Subject":"الموضوع",
    "Title":"العنوان",
    "Send":"ارسال",
    "Serial":"رقم تسلسلي",
    "Image":"الصورة",
    "Source Country":"بلد المصدر",
    "Destination Country":"بلد الوجهة",
    "Urgent Request Details":"تفاصيل الطلب العاجل",
    "From":"من",
    "To":"إلى",
    "Source Info":"معلومات المصدر",
    "Destination Info":"معلومات الوجهة",
    "Source City Name":"اسم مدينة المصدر",
    "Source Port Name":"اسم ميناء المصدر",
    "destination City Name":"اسم مدينة الوجهة",
    "destination Port Name":"اسم ميناء الوجهة",
    "Price Offer Details":"تفاصيل طلب عرض الاسعار",
    "Welcome":"اهلا بكم",
    "Thank you for using our services":"شكرا لاستخدامك خدماتنا",
    "Points":"نقطة",
    "You have":"لديك",
    "Equivalent to":"وتقابل",
    "Valid on":"صالحة لغاية",
    "Question":"الاستفسار",
    "Answer":"الجواب",
    "answerDate":"تاريخ الجواب",
    "Waiting For Answer":"انتظار",
    "B2B Products":"منتجات B2B",
    "B2C Products":"منتجات B2C",
    "Add Product B2B":"اضافة منتج B2B",
    "Add Product B2C":"اضافة منتج B2C",
    "English Name":"الاسم الانكليزي",
    "Arabic Name":"الاسم العربي",
    "Arabic description":"الوصف بالعربية",
    "English description":"الوصف بالانكليزية",
    "Add Product":"اضافة المنتج",
    "coast":"التكلفة",
    "Checkout":"الدفع",
    "Product Information":"معلومات المنتجات",
    "check":"تحقق",
    "code":"كود الكوبون",
    "Coupon Is Valid":"هذا الكوبون صالح",
    "Coupon Is Not Valid":"هذا الكوبون غير صالح",
    "Tel":"تلفون",
    "United Arab Emarates":"الإمارات العربية المتحدة",
    "message":"الرسالة",
    "clear":"مسح",
    "company":"شركة",
    "services":"الخدمات",
    "Our Services":"خدماتنا",
    "Event Reservation":"حجز مناسبة",
    "sign up client":"تسجيل جديد - زبون فرد",
    "sign-up as client":"تسجيل جديد كزبون",
    "sign up company":"تسجيل جديد - زبون شركة",
    "sign up influencer":"تسجيل جديد - مؤثر اجتماعي",
    "sign-up as influencer":"تسجيل جديد كمؤثر اجتماعي",
    "Products Categories":"فــئات المنتجات",
    "Products":"المنتجات",
    "Recently Arrived":"وصل حديثاً",
    "Our Branches":"فروعـــنا",
    "Media Center":"المركز الإعلامي",
    "The cart is empty":"سلة المشتريات فارغة",
    "Book a Appointment ":"حجز موعد",
    "Advantages":"مزايا",
    "Videos":"الفيديو",
    "Pictures":"الصور",
    "Book":"احجز",
    "Region":"المنطقة",
    "District":"الحي",
    "Block Number":"رقم العقار",
    "Payment Method":"طريقة الدفع",
    "Booking Price":"قيمة الحجز",
    "Payment Date":"تاريخ الدفع",
    "Voucher Number":"رقم الوصل",
    "Date":"التاريخ",
    "Hours":"الساعة",
    "You may also like":'ربما يعجبك أيضا',
    "Holiday":"العطلات",
    "Order-Code": "كود الطلب",
    "Created-Date": "تاريخ الطلب",
    "Total-Price": "السعر الاجمالي",
    "details": "التفاصيل",
    "Current-Password": "كلمة السر الحالية",
    "New-Password": "كلمة السر الجديدة",
    "Confirmed-Password": "تأكيد كلمة السر",

    //000000000000000000000000000000






    "my-profile": "حسابي الشخصي",

  "communication":"تواصل معنا",
    
    "Membership registration":"تسجيل العضوية",
    "club-registration":"تسجيل نادي",
    "register":"تسجيل",
    "Name according to passport":"الإسم حسب جواز السفر",
    "Current job and organization":"الوظيفة الحالية و المؤسسة",
    "Academic qualification and specialization":"المؤهل العلمي و التخصص",

    "date of birth":"تايخ الميلاد",
    "Photograph":"صورة شخصية",
    "photo of passport":"صورة عن جواز السفر",
    "A copy of the press card":"صورة البطاقة الصحفية",
    "A copy of the Emirates ID":"صورة الهوية الإماراتية",
    "A copy of the Emirates ID - front face":"صورة الهوية الإماراتية - الوجه الأمامي",
    "A copy of the Emirates ID - back face":"صورة الهوية الإماراتية - الوجه الخلفي",
    "fileToWhomItMayConcern": "ملف إلى من يهمه الأمر",
    
    "confirmed-password": "تأكيد كلمة المرور",
    
    "princedom":"الإمارة",
    "Attachments":"المرفقات",

    "downloadFile":"تحميل الملف",
    "Load More":"تحميل المزيد",

    "sign-in": "تسجيل دخول",
    
    "qualification":"المؤهلات",

    "Halls":"القاعات",
    "Number":"الرقم",
    "Capacity":"الصفة",
    "Floor":"الطابق",
    "Availability":"الإتاحية",
    "Not Available":"غير متاح",
    "Available":"متاح",
    "Reserve":"حجز",
    "ReserveHall":"حجز القاعة",
    "confirm":"تثبيت",
    "fromDate":"تاريخ البدء",
    "toDate":"تاريخ الانتهاء",

    "Accepted":"تم القبول",
    "Refused":"مرفوض",
    "default":"الافتراضي",

    "rating":"التقييم",

    "There are no reviews":"لا يوجد تقييمات",
    "No comments":"لا يوجد تعليقات",
    "comment":"تعليق",
    "Last Name of Company Contact":"الاسم الأخير لجهة الاتصال بالشركة",
    "Company Contact Email Address":"عنوان البريد الإلكتروني لجهة الاتصال بالشركة",

    "Company Website":"الموقع الإلكتروني للشركة",
    "Company Phone Number":"رقم هاتف الشركة",
    "Company Mobile Phone":"شركة الهاتف المحمول",
    "Street address for registered business":"عنوان الشارع للأعمال التجارية المسجلة",
    "Apt / Suite":"شقة / جناح",
    "Continue":"متابعة",
    "Add new Adress":"أضف عنوانًا جديدًا",
    "Office Phone":"هاتف المكتب",
    "alladdress":"العناوين",
    "Post town":"بريد المدينة",
    "streetAddress":"اسم الشارع",
    "Adress name":"اسم العنوان",
    "Company Billing Information":"معلومات فواتير الشركة",
    "Fill out the additional information":"تعبئة المعلومات الإضافية",
    "First Name of Billing Contact":"الاسم الأول لجهة اتصال الفواتير",
    "The name of the person responsible for the company in Arabic":"اسم الشخص المسؤول عن الشركة بالعربي",
    "Name of the person responsible for the company":"اسم الشخص المسؤول عن الشركة  ",
    "Phone number of the person in charge of the company":"رقم هاتف الشخص المسؤول عن الشركة  ",
    "Email of the person responsible for the company":"البريد الإلكتروني للشخص المسؤول عن الشركة",
    "Last Name of Billing Contact":"الاسم الأخير لجهة اتصال الفواتير",
    "Billing Email Address":"عنوان البريد الإلكتروني للفوترة",
    "Billing Phone Number":"الفواتير رقم الهاتف",
    "Postal Code":"رمز بريدي",
    "Next":"التالي",
    "Prev":"السابق",
    "Information of the person responsible for the company":"معلومات الشخص المسؤول عن الشركة",
    "Tax Exemption and Business Certificate Enrollment":"الإعفاء الضريبي وتسجيل شهادة الأعمال",
    "upload your completed resale certificate in which you are likely to ship.":"قم بتحميل شهادة إعادة البيع المكتملة التي من المحتمل أن تقوم بالشحن بها.",
    "Upload resale certificate, business certificate in which you are registered and/or will be conducting business.":"قم بتحميل شهادة إعادة البيع وشهادة الأعمال التي قمت بالتسجيل فيها و/أو ستزاول أعمالك.",
    "First Name of Company Contact":"الاسم الأول لجهة اتصال الشركة",
    "Are you registered as a reseller for sales tax purposes or have a business certificate?":"هل أنت مسجل كموزع لأغراض ضريبة المبيعات أو لديك شهادة تجارية؟",
    "Any additional information you would like to share with us?":"هل هناك أي معلومات إضافية تود مشاركتها معنا؟",
    "How did you learn about MARBYA CHARM?":"كيف تعرفت على MARBYA CHARM؟",
    "What areas of interest would you like to hear about?":"ما هي مجالات الاهتمام التي تود أن تسمع عنها؟",
    "Yes":"نعم",
    "No":"لا",
    "Would you like to receive product updates, inspiration, news, and special offers from MARBYA CHARM?":"هل ترغب في تلقي تحديثات المنتج والإلهام والأخبار والعروض الخاصة من MARBYA CHARM؟",
    "Enter Your Email Adress":"ادخل البريد الإلكتروني",
    "StreetAddress2":"العنوان الثاني",
    "StreetAddress1":"العنوان الأول",
    "firstname":"الاسم الأول",
    "lastname":"الاسم الاخير",
    "glamorousdes":"أدخل عالم الفخامة المصممة حسب الطلب في متجرنا الساحر، حيث يلتقي الرقي بالتخصيص. استكشف مجموعتنا المنتقاة من العناصر الحصرية، المصنوعة بدقة من مواد متميزة لتجسد الأناقة الخالدة. اطلب القطعة المرغوبة مسبقًا للشروع في رحلة التخصيص، حيث يمكن تصميم كل التفاصيل وفقًا لمواصفاتك الدقيقة. فريقنا اليقظ موجود هنا لإرشادك خلال هذه العملية، مما يضمن تحقيق رؤيتك من خلال براعة لا مثيل لها واهتمام بالتفاصيل.ارفع من أسلوبك بلمسة من الفخامة الفريدة لك.",
    "fullName":"الاسم الكامل",

    "Edit-Profile":"تعديل الحساب ",

    "nameAr": "الاسم العربي",
    "nameEn": "الاسم الانجليزي",
    "responsiblePersonNameAr": " اسم السخص المسوول ",
    "responsiblePersonNameEn": "اسم السخص المسوول بالانجليزي",
    "responsiblePersonNamePhon": "هاتف السخص المسوول ",

    "personal": "شخصي",
    "person": "شخص",
    "comapny": "شركة",
    "full-name": "الاسم الكامل",

    "full-name-ar":"الاسم الكامل بالعربي ",
    "company-name": "اسم الشركة",

    "select-country": "حدد الدولة",
    "submit": "تقديم طلب",
    "or": "أو",
    "basket": "السلة",
    "loading":"تحميل",
    "unpaid":"غير مدفوعة",
    "paid":"مدفوعة",
    "Your Name":"الاسم",
    "Disclaimer_responsibility": "إخلاء المسئولية",
    "more-inforamtion": "معلومات اضافية",
    "commercial-license-num": "رقم الرخصة التجارية",
    "commercial-license-date": "تاريخ الرخصة التجارية",
    "General_questions": "اسئلة عامة",
    "Your search results For": "نتائج البحث عن",
    "search_by_name": "ابحث عن اسم المنتج",
    "Orders": "طلباتي",
    "newarrivaledesc":"صمم تحفة المعيشة الخاصة بك مع مجموعتنا المنسقة، لأن منزلك هو لوحة حياتك، وكل قطعة تحكي قصة من الأناقة الخالدة",
    "Show_Detail": "اعرض التفاصيل",
    "Photogallery": "معرض الصور",
    "Cart-Totals": "إجمالي السلة",
    "Bills": "الفواتير",
    "Select City": "اختر المدينة",
    "City":"المدينة",
    "Select Country": "اختر البلد",
    "additional information":"معلومات إضافية",
    "Please fill out the following fields":"يرجى تعبئة الحقول التالية أو",
    "companyNumber":" رقم الشركة",
    "companyWebsite":"الموقع الإلكتروني للشركة",
    "companyName":"اسم الشركة",
    "Favorite": "المفضلة",
    "Skip":"تخطي",
    "Cart": "السلة",
    "Welcome to our extraordinary world of furniture where design meets functionaly and craftsmanship meets innovation": "مرحبًا بكم في عالم الأثاث الاستثنائي لدينا حيث يلتقي التصميم مع الأداء الوظيفي والحرفية مع الابتكار",
    "furniture": "أثاث",
    "Latest News, Events, and Offers": "آخر الأخبار , الأحداث, والعروض",
    "Subsicribe": "اشتراك",
    "Ener Email Address": "ادخل عنوان البريد الالكتروني"
  }
});