export const useEn = () => useState(() => {
  return{
    "page":"page",
    "dashboard":"dashboard",
    "accounts":"accounts",
    "block":"block",
    "blocks":"blocks",
    "image":"image",
    "new-block":"new block",
    "courses":"courses",
    "login-failed":"Sorry, an error occurred while trying to log in. Please ensure that your Email and password are correct and try again. If the issue persists, please contact technical support.",
    "order":"order",
    "isActive":"active",
    "type":"type",
    "english":"english",
    "arabic":"arabic",
    "icon":"icon",
    "content":"content",
    "add-description":"add description",
    "add-field":"add field",
    "page-size":"page size",
    "add":"add",
    "logged-in-successfully":"logged in successfully.",
    "valid-email":"please enter valid email",
    "required-field":"required field",
    "sent-successfully":"The information has been sent successfully",
    "hire-date":"hire date",
    "job-title":"job title",
    "manager-details":"manager details",
    "coach-details":"coach details",
    "player-details":"player details",
    "player-name":"player name",
    "back":"back",
    "Finished":"Finished",
    "Not Yet":"Not Yet",
    "group":"group",
    "match-num":"match number",
    "coaches":"coaches",
    "managers":"managers",
    "click-to-download":"click to download",
    "drop-the-files-here":"Drop the files here",
    "approve":"approve",
    "approve-termination":"Do you really want to terminate a contract: ",
    "contract-termination":"contract termination",
    "edit-and-renewal":"edit and renewal",
    "runs":"runs",
    "result":"result",
    "referee":"referee",
    "playground":"playground",
    "matches":"matches",
    "team":"team",
    "position":"position",
    "remain":"remain",
    "loss":"loss",
    "won":"won",
    "played":"played",
    "upcoming-matches":"Upcoming Matches",
    "matches-management":"Matches Management",
    "arrangement":"Arrangement",
    "winner":"winner",
    "role":"role",
    "season":"season",
    "players":"players",
    "foundation-year":"Foundation Year",
    "report":"report",
    "date":"date",
    "Reject":"Reject",
    "Accept":"Accept",
    "Renew Managers":"Renew Managers",
    "New Managers":"New Managers",
    "Renew Coach":"Renew Coach",
    "New Coach":"New Coach",
    "Renew Player":"Renew Player",
    "New Player":"New Player",
    "Matches Management":"Matches Management",
    "Order Management":"Order Management",
    "Coaches and Manager Management":"Coaches and Managers Management",
    "Player Management":"Player Management",
    "Team management":"Team management",
    "logo":"logo",
    "certificates":"certificates",
    "notes":"notes",
    "no-data":"No data",
    "add-attachment":"add attachment",
    "attachment-name":"attachment name",
    "attachment":"attachment",
    "guardian-acknowledgment-photo":"guardian acknowledgment photo",
    "member-form-photo":"player form photo",
    "player-photo":"player photo",
    "coach-photo":"coach photo",
    "manager-photo":"manager photo",
    "manager-form-photo":"manager form photo",
    "coach-form-photo":"coach form photo",
    "player-form-photo":"player form photo",
    "passport-photo":"passport photo",
    "ID-photo":"ID photo",
    "player-number":"player number",
    "international-classification":"international classification",
    "national-team":"national-team",
    "local-classification":"local classification",
    "passport-number":"passport number",
    "ID-number":"ID number",
    "registration-number":"registration number",
    "registration":"registration",
    "age-category":"age category",
    "Federation-Championships-And-Events":"Federation Championships And Events",
    "Matchs":"Matchs",
    "daily-reservation-fee":"Daily Reservation Fee",
    "Worker":"Worker",
    "Affiliate":"Affiliate",
    "show-more":"show more",
    "search-results":"search results",
    "no-matching-results":"no matching results",
    "identification-photo":"identification photo",
    "salary-receipt":"A photo of the salary receipt",
    "price-after-discount":"price after discount",
    "You are a subscriber to the Solidarity Fund":"You are a subscriber to the Solidarity Fund.",
    "Your request has been sent successfully.":"Your request has been sent successfully.",
    "new-member-fee":"New member subscription fee",
    "server-error":"Server Error, Please communicate with the administration to solve the problem",

    "false":"no",
    "true":"yes",
    "active":"active",
    "inactive":"inactive",
    "Letter-Of-Commitment-From-Employer":"Letter Of Commitment From Employer",
    "last-installement-amount":"last installement amount",
    "installement-amount":"installement amount",
    "for-expatriates":"Upload a copy of the passport with a valid residence permit for expatriates",
    "membership-number":"membership number",
    "membership-type":"membership type",
    "mailbox":"mailbox",
    "job-address":"job address",
    "loan-id":"loan id",
    "date":"date",
    "new-loan":"new loan",
    "current-loan":"current loan",
    "previous-loans":"Previous loans",
    "reservations-and-subscriptions":"Reservations and subscriptions",
    "reservations":"reservations",
    "subscriptions":"subscriptions",

    "accepted-loans":"accepted loans",
    "pending-loans":"pending loans",
    "nothing":"nothing",
    "no-installments-paid-yet":"No installments paid yet",
    "rest":"rest",
    "sum-payment-amounts":"sum payment amounts",
    "payment-amount":"payment amount",
    "num":"num",
    "installments":"installments",
    "loan-installment":"installments of loan",
    "A copy of the qualification license":"A copy of the qualification license",
    "job-address":"job address",
    "job":"job",
    "guest-registration":"guest registration",
    "search-the-association":"Search the association",
    "what-are-you-looking-for?":"what are you looking for?",
    "loan":"loan",
    "loan-of-solidarity-fund":"loan of solidarity fund",
    "review-solidarity-fund-req":"Your application for subscription to the Solidarity Fund has been received and is under review.",
    "loan-amount":"Loan amount in AED",
    "solidarity-fund":"solidarity fund",
    "Start Date":"Start Date",
    "End Date":"End Date",
    "End Subscription":"End Subscription",
    "Emirate":"Emirate",
    "Price":"Price",
    "Discount":"Discount",
    "exhibitions":"exhibitions",
    "exhibition":"exhibitions",
    "membership":"Membership",
    "membership-renewal":"Membership renewal",
    "Renewal of membership in the Journalists Association":"Renewal of membership in the Journalists Association",
    "Subscription to the Arab Journalists Union":"Subscription to the Arab Journalists Union",
    "Subscribe to the International Union of Journalists":"Subscribe to the International Union of Journalists",
    "membership-status":"Membership status",
    "submit-renewal":"Submit a membership renewal request",
    "submit-membership-request":"Submit a membership request",
    "submit-solidarity-fund-subscribes":"Submit an application for subscription to the Solidarity Fund",
    "read-more":"read more",
    "journalists-unions-and-associations":"journalists' unions and associations",
    "journalists-from-the-beautiful-era":"journalists from the beautiful era",
    "number-of-members":"number of members",
    "number-of-events":"number of events",
    "show-all":"show all",
    "activities":"activities",
    "activity":"activity",
    "refresh":"refresh",
    "membership-registration":"membership registration",
    "and":"and",
    "sponsors":"sponsors",
    "sponsor":"sponsor",
    "friendly-sites":"Friendly sites",
    "friendly-site":"Friendly site",
    "most-view":"most view",
    "menu":"menu",
    "less":"less",
    "back-to-home":"back to home",
    "page-not-found":"page not found",
    "could-not-find-page-msg":"could not find the page",
    "error-occurred-msg":"an error occurred",
    "server-error":"server error",
    "appointment-date": "Appointment Date",
    "appointment-time": "Appointment Time",
    "wait-registration": "Please wait while registration is completed",
    "wait": "Please wait",
    "otheradv":"Similar properties",
    "Payment plan":"Payment plan",
    "Project brochure":"Project brochure",
    "bathroom":"Bathroom",
    "Number of rooms":"Number of rooms",
    "Property area":"Property area",
    "floorNumber":"floorNumber",
    "projectNumber":"Project Number",
    "realtyStatus":"Realty Status",
    "name":"Name",
    "mapRealty":"Realty Map",
    "realtyValue":"Realty Value",
    "realltyContract":"Reallty Contract",
    "Building number":"Building number",
    "room":"Room",
    "The property is not available now":"The property is not currently available for reservation",
    "RoomCount":"Room Count",
    "Appointment Booking":"Appointment Booking",
    "Reserve the Realty":"Reserve the Realty",
    "Real Estate":"Real Estate",
    "Book a property":"Book a property",
    "Property Details":"Property Details",
    "Book an Appointment":"Book an Appointment",
    "About Us": "About Us",
    "About the project": "About the project",
    "Change Language": "Change Language",
    "An overview of the developing company": "An overview of the developing company",
    "Speech of the Chairman of the Board of Directors": "Speech of the Chairman of the Board of Directors",
    "Vision, mission and goals": "Vision, mission and goals",
    "Our projects": "Our Projects",
    "Project Name": "Project Name",
    "Details about the project": "Details about the project",
    "Al-Sabari Building": "Al-Sabari Building",
    "Al-Saabari Building Project Al-Saabari Building Project Al-Saabari Building Project Al-Saabari Building Project Al-Saabari Building Project Al-Saabari Building Project": "Al-Saabari Building Project Al-Saabari Building Project Al-Saabari Building Project Al-Saabari Building Project Al-Saabari Building Project Al-Saabari Building Project",
    "Project Detail": "Project Detail",
    "The mosque": "The mosque",

    "Reserve the property": "Reserve the property",
    "Name": "Name",
    "Phone Number": "Phone Number",
    "Second Phone Number": "Second Phone Number",
    "Building number (or building name)": "Building number (or building name)",
    "Apartment number": "Apartment number",
    "Contact Us": "Contact Us",
    "Address": "Address",
    "message": "Message",
    "job opportunities": "job opportunities",
    "Frequently_Asked_Questions": "Frequently Asked Questions",
    "News": "News",
    "Videos": "Videos",
    "Welcome_To_Frequently_Asked_Questions": "Welcome To Frequently Asked Questions",
    "Here_you_can_find_the_answers_youre_looking for": "Here you can find the answers youre looking for",
    "Sponsers": "Sponsers",
    "AL SABARI RESIDENCE": "AL SABARI RESIDENCE",
    "This future project have several nearby landmarks such as Kent College Dubai, Kent Nursery Dubai, Champions Karate Academy, Meydan South Villas, Zen Star Badminton Academy, United Football Club Dubai, Meydan South Villas, LLFPM School, Nad Al Sheiba Mini Forest Trail, etc": "This future project have several nearby landmarks such as Kent College Dubai, Kent Nursery Dubai, Champions Karate Academy, Meydan South Villas, Zen Star Badminton Academy, United Football Club Dubai, Meydan South Villas, LLFPM School, Nad Al Sheiba Mini Forest Trail, etc.",
    "Public facilities": "Public facilities",
    "swimming pool": "swimming pool",
    "supermarket": "super market",
    "Tennis Court": "Tennis Court",
    "Incubation": "Incubation",
    "Open yard": "Open yard",
    "Dressing Room": "Dressing Room",
    "Basketball": "Basketball",
    "Mosque": "Mosque",
    "Running track": "Running track",
    "Visitors' position": "Visitors' position",
    "Download Bruchures": "Download Bruchures",
    "The community is divided into different parcels: the west edge of District 11, adjacent to Al Ain Road": "The community is divided into different parcels: the west edge of District 11, adjacent to Al Ain Road",
    "Parcels C, D & L, are planned as medium density (G+5 apartments), located between Al Ain Road and the low density parcels (villas) to the east": "Parcels C, D & L, are planned as medium density (G+5 apartments), located between Al Ain Road and the low density parcels (villas) to the east",
    "explore": "Explore",
    "Detail": "Detail",
    "Floor plans": "Floor plans",
    "Search": "Search",
    "clearfilter": "Clear Filter",
    "pricelow": "Low Price",
    "pricehigh": "High Price",
    "realtyType": "Realty Type",
    "Building": "Building",
    "Register your interest now": "Register your interest now",
    //==============================
    "lang":"عربي",
    "best-seller":"best seller",
    "conform":"conform",
    //==============================
    "Company-Arabic-Name":"Company Arabic Name",
    "Company-English-Name":"Company English Name",
    "Arabic-Responsible-Person-Name":"Arabic Responsible Person Name",
    "English-Responsible-Person-Name":"English Responsible Person Name",
    "Responsible-Person-Mobile":"Responsible Person Mobile",
    "Pending":"Pending",
    "influencer":"Influencer",
    "influencers":"Influencers",
    "events":"Events",
    "book-online":"Book Online",
    "search":"search",
    "choose-a-platform":"choose a platform",
    "subscribe-to-our-mail":"Subscribe to our mailing list",
    "book-now":"Book Now",
    "client":"Client",
    "followers":"Followers",
    "photos":"photos",
    "packages":"packages",
    "my-packages":"my packages",
    "our-packages":"our packages",
    "similar-packages":"similar packages",
    "similar-products":"similar products",
    "empty":"empty",
    "new-package":"new package",
    "package-name-in-english":"package name in english",
    "package-name-in-arabic":"package name in arabic",
    "description-in-english":"description in english",
    "description-in-arabic":"description in arabic",
    "package-type":"package type",
    "add-new-package":"add new package",
    "edit":"edit",
    "delete":"delete",
    "social-media-url": "social media url",
    "social-media-type": "social media type",
    "add-new-social-media":"add new social media",
    "bio":"bio",
    "additional-info":"additional info",
    "influencers-packages":"influencers packages",
    "website-packages":"website packages",
    "website-services":"website services",
    "our-services":"our services",
    "your-order":"your order",
    "cancel":"cancel",
    "package-name":"package name",
    "news":"news",
    "show-profile":"show profile",
    "show-package":"show package",
    "Photo-album":"Photo album",
    "Video-album":"Video album",
    "old-price":"old price",
    "new-price":"new price",
    "months":"months",
    "about-me":"about me",
    "note1":"add some information about you",
    "note2":"no information to show",
    "newsall":"All News",
    "print":"print",
    //============
    "follow-us":"Follow Us",
    "occasions-and-holidays":"Occasions and Holidays",
    "On_Our_Site":"On Our Site",
    "Log_in_to_get_all_our_services":"Log in to get all our services",
    "User_Name":"User Name",
    "Password":"Password",
    "Register Now":"Register Now",
    "Register":"Register",
    "Individual registration":"Individual Registration",
    "Company registration":"Company Registration",
    "Log_In":"Log In",
    "country":"Country",
    "My-Profile":"My Profile",
    "reset-password" : "reset password",
    "Change-Password" : "Change Password",
    "city":"City",
    "nameCompany":"Company Name",
    "Employment":"Employment",
    "nameResponsible":"Name of responsible person",
    "candy":"Candy",
    "gift":"GIFTS",
    "flower":"Flower",
    "AED":"AED",
    "actions":"Actions",
    "our-latest-products":"Our Latest Products",
    "latest-products":"Latest Products",
    "Cart Shop":"Cart Shop",
    "hello": "Hello",
    "language": "English",
    "sign-up": "Sign Up",
    "login": "Login",
    "logout" : "Logout",
    "email" : "Email",
    "username" : "Username",
    "fullname" : "full name",
    "fullnameEn" : "full name En",
    "fullnameAr" : "full name Ar",
    "fullnameEnc" : "Company name En",
    "fullnameArc" : "Company Name Ar",
    "fullnameInfluencer" : "Influencer Name",
    "fullnameInfluencerAr" : "Influencer Name in Arabic",
    "fullnameInfluencerEn" : "Influencer Name in English",
    "password" : "Password",
    "confirmpassword" : "Confirmed Password",
    "gender" : "Gender",
    "website" : "Website",
    "address" : "Address",
    "englishAddress" : "English Address",
    "arabicAddress" : "Arabic Address",
    "birthDate" : "Birth Date",
    "phone" : "Phone Number",
    "mobile" : "Mobile Number",
    "home" : "Home",
    "profile" : "Profile",
    "editeprofile" : "Edite Profile",
    "my-account" : "My Account",
    "about-us" : "About Us",
    "gallery" : "Gallery",
    "photo-gallery" : "Photo Gallery",
    "contact-us" : "Contact us",
    "contact" : "Contact",
    "how-it-work" : "How It Work",
    "more": "More",
    "offers": "Offers",
    "special-offers": "special offers",
    "craft-your-prepaid-card": "CRAFT YOUR PREPAID CARD",
    "craft-your-card": "CRAFT YOUR CARD",
    "faq": "FAQ",
    "what-we-do": "What We Do",
    "privacy-policy": "Privacy Policy",
    "returns-and-refunds": "Returns and Refunds",
    "terms-conditions": "Terms & Conditions",
    "view-all": "View All",
    "view-more": "View More",
    "our-products": "Our Products",
    "send": "Send",
    "Dear Sir/Madam, I am looking for products with the following specifications:":"Dear Sir/Madam, I'm looking for products with the following specifications:",
    "type-your-name": "Type Your Name",
    "type-your-email": "Type Your Email",
    "type-your-subject": "Type Your Subject",
    "type-your-message": "Type Your Message",
    "login-to-enter": "Log in to enter",
    "forgot-password": "Forgot Password",
    "select-metal": "Select Metal",
    "card-number": "Card Number",
    "card-number-two": "Card Number Two",
    "card-number-one": "Card Number One",
    "orders": "Orders",
    "arabicName": "Arabic Name",
    "englishName": "English Name",
    "passport-arabicName": "Name in Arabic according to the passport",
    "passport-englishName": "Name in English according to the passport",
    "loggedInMandatory": "You Must Be Logged In To Continue The Process",
    "small": "Small ( Rectangular )",
    "large" : "Large ( Square )",
    "next": "Next",
    "previous": "Previous",
    "shipping-cost": "Shipping Cost",
    "cache": "Cache",
    "online": "Online",
    "order-now": "Order Now",
    "with-shipping": "With Shipping",
    "without-shipping": "Without Shipping",
    "with-warranty": "With warranty",
    "without-warranty": "Without warranty",
    "product-information": "Product Information",
    "user-information": "User Information",
    "shipping-warranty": "Shipping & warranty",
    "payment" : "Payment",
    "countries" : "Countries",
    "nationality" : "Nationality",
    "select-countries" : "Select Country",
    "cities" : "Cities",
    "card-care" : "Card Care",
    "card-price" : "Card Price",
    "care-price" : "Care Price",
    "our-designer-price" : "Our Designer Price",
    "total-card-price" : "Total Card Price",
    "select-cities" : "Select Cities",
    "shipping-price" : "Shipping Price",
    "warranty-price" : "warranty Price",
    "total-price" : "Total Price",
    "final-price" : "Final Price",
    "continue-process" : "Continue Process",
    "continue" : "Continue",
    "add-to-cart": "Add To Cart",
    "color-name" : "Color Name",
    "select-color" : "Select Color",
    "server-error": "Server Error, Please communicate with the administration to solve the problem",
    "save": "Save",
    "no": "No",
    "yes": "Yes",
    "text-one": "Text One",
    "text-two": "Text two",
    "category":"Category",

    "Customer_Service":"Customer Service",
    "My_Cart":"My Cart",
    "Shop_By_Brands":"Shop By Brands",
    "Shop":"Shop",
    "Offers":"Offers",
    "Links":"Links",
    "Invoices":"Invoices",
    "Message":"Message",
    "Customer Care":"Customer Care",
    "empty-cart": "Empty Cart",
    "product-name": "Product Name",
    "amount": "Amount",
    "quantity": "Quantity",
    "price": "Price",
    "product-image": "Product Image",
    "password-not-valid": "Password must contain at least one capital letter and lowercase letter",
    "no-data": "No Data To Display",
    "load-more": "Load More...",
    "Services & Suppliers":"Services & Suppliers",
    "Country":"Country",
    "Suppliers Membership":"Suppliers Membership",
    "Suppliers Registration":"Suppliers Registration",
    "Suppliers Login":"Suppliers Login",
    "Added value Services":"Added value Services",
    "Urgent Request":"Urgent Request",
    "Request For Quotation":"Request For Quotation",
    "Trading Service":"Trading Service",
    "Trading Insurance":"Trading Insurance",
    "Logistic Services":"Logistic Services",
    "CHOOSE COUNTRY":"CHOOSE COUNTRY",
    "United Arab Emirates":"United Arab Emirates",
    "Sudan":"Sudan",
    "Suppliers Services":"Suppliers Services",
    "Categories":"Categories",
    "subcategory":"subcategory",
    "Type":"Type",
    "Company Sector":"Company Sector",
    "Free delivery on first order":"Free delivery on first order",
    "Cach on delivery":"Cach on delivery",
    "Free returns":"Free returns",
    "Limmited Offers":"Limmited Offers",
    "More":"More",
    "Subscribe":"Subscribe",
    "Order":"Order",
    "Home":"Home",
    "Shop By":"Shop By",
    "Products Details":"Products Details",
    "Description":"Description",
    "OTHER SIMILAR PRODUCTS":"OTHER SIMILAR PRODUCTS",
    "Join free":"Join free",
    "Forget Your Password":"Forget Your Password",
    "Remember me":"Remember me",
    "If you don’t have an account please":"If you don’t have an account",
    "Customer":"Customer",
    "Wholesale":"Wholesale",
    "Required field":"Required field",
    "Optional field":"Optional field",
    "fax":"Fax",
    "mailBox":"Mail Box",
    "Male":"Male",
    "Female":"Female",
    "Responsible Person Name Ar":"Responsible Person Name Ar",
    "Responsible Person Name En":"Responsible Person Name En",
    "Responsible Person Mobile":"Responsible Person Mobile",
    "Please Login To Your Account Then Send":"Please Login To Your Account Then Send",
    "Tell suppliers what you need":"Tell suppliers what you need",
    "Complete your Urgent Request":"Complete your Urgent Request",
    "The more specific your information, the more accurately we can match your request to the right suppliers":"The more specific your information, the more accurately we can match your request to the right suppliers",
    "Exporting country information":"Exporting country information",
    "Importing country information":"Importing country information",
    "cityAr":"City Arabic",
    "cityEn":"City English",
    "portar":"Port Arabic",
    "porten":"Port English",
    "Drag and drop files here, or Click to select files":"Drag and drop files here, or Click to select files",
    "I have read, understood and agreed to abide by Terms and Conditions Governing Urgent Request":"I have read, understood and agreed to abide by Terms and Conditions Governing Urgent Request",
    "Submit Urgent Request":"Submit Urgent Request",
    "Complete your RFQ":"Complete your RFQ",
    "Submit RFQ":"Submit RFQ",
    "Complaints And Suggestions":"Complaints And Suggestions",
    "Urgent Requests":"Urgent Requests",
    "RFQ":"RFQ",
    "Inquiries":"Inquiries",
    "My balance (Reward points)":"My balance (Reward points)",
    "full Name":"full Name",
    "Company Name":"Company Name",
    "Responsible Person Name":"Responsible Person Name",
    "Order Number":"Order Number",
    "Order date":"Order date",
    "Status":"Status",
    "Action":"Action",
    "Details":"Details",
    "Back":"Back",
    "Order Details":"Order Details",
    "Payment Status":"Payment Status",
    "Created Date":"Created Date",
    "Order Tracking":"Order Tracking",
    "Subject":"Subject",
    "Title":"Title",
    "Send":"Send",
    "Serial":"Serial",
    "Image":"Image",
    "Source Country":"Source Country",
    "Destination Country":"Destination Country",
    "Urgent Request Details":"Urgent Request Details",
    "From":"From",
    "To":"To",
    "Source Info":"Source Info",
    "Destination Info":"Destination Info",
    "Source City Name":"Source City Name",
    "Source Port Name":"Source Port Name",
    "destination City Name":"destination City Name",
    "destination Port Name":"destination Port Name",
    "Price Offer Details":"Price Offer Details",
    "Welcome":"Welcome",
    "Thank you for using our services":"Thank you for using our services",
    "Points":"Points",
    "You have":"You have",
    "Equivalent to":"Equivalent to",
    "Valid on":"Valid on",
    "Question":"Question",
    "Answer":"Answer",
    "answerDate":"answer Date",
    "Waiting For Answer":"Waiting For Answer",
    "B2C Products":"B2C Products",
    "B2B Products":"B2B Products",
    "Add Product B2B":"Add Product B2B",
    "Add Product B2C":"Add Product B2C",
    "English Name":"English Name",
    "Arabic Name":"Arabic Name",
    "Arabic description":"Arabic description",
    "English description":"English description",
    "Add Product":"Add Product",
    "coast":"Coast",
    "Checkout":"Checkout",
    "Product Information":"Product Information",
    "check":"Check",
    "code":"Coupon Code",
    "Coupon Is Valid":"Coupon Is Valid",
    "Coupon Is Not Valid":"Coupon Is Not Valid",
    "Tel":"Tel",
    "United Arab Emarates":"United Arab Emarates",
    "clear":"Clear",
    "company":"Company",
    "services":"Services",
    "Our Services":"Our Services",
    "Event Reservation":"Event Reservation",
    "sign up client":"Sign Up - Client",
    "sign-up as client":"sign-up as client",
    "sign up company":"Sign Up - Company",
    "sign up influencer":"Sign Up - Influencer",
    "sign-up as influencer":"sign-up as influencer",
    "Products Categories":"Products Categories",
    "Products":"Products",
    "Recently Arrived":"Recently Arrived",
    "Our Branches":"Our Branches",
    "Media Center":"Media Center",
    "The cart is empty":"The cart is empty",
    "Book a Appointment":"Book a Appointment",
    "Advantages":"Advantages",
    "Pictures":"Pictures",
    "Book":"Book",
    "Region":"Region",
    "District":"District",
    "Block Number":"Block Number",
    "Payment Method":"Payment Method",
    "Booking Price":"Booking Price",
    "Payment Date":"Payment Date",
    "Voucher Number":"Voucher Number",
    "Date":"Date",
    "Hours":"Hours",
    "You may also like":'You may also like',
    "Holiday":"Holiday",
    "Order-Code": "Order Code",
    "Created-Date": "Created Date",
    "Total-Price": "Total Price",
    "Current-Password": "Current Password",
    "New-Password": "New Password",
    "Confirmed-Password": "Confirmed Password",
    "my-profile": "My Profile",
    "Can a broker help you?": "Can a broker help you?')",
    "communication":"Conatct Us",
    "date of birth":"Date of Birth",
    "Photograph":"Photograph",
    "photo of passport":"Photo of passport",
    "A copy of the press card":"A copy of the press card",
    "A copy of the Emirates ID":"A copy of the Emirates ID",
    "A copy of the Emirates ID - front face":"A copy of the Emirates ID - front face",
    "A copy of the Emirates ID - back face":"A copy of the Emirates ID - back face",
    "fileToWhomItMayConcern": "file to whom it may concern",
    "Membership registration":"Membership registration",
    "club-registration":"club registration",
    "register":"register",
    "Name according to passport":"Name according to passport",
    "Current job and organization":"Current job and organization",
    "Academic qualification and specialization":"Academic qualification and specialization",
    "confirmed-password": "Confirmed Password",
    "princedom":"Princedom",
    "Attachments":"Attachments",
    "downloadFile":"Download File",
    "Load More":"Load More",
    "sign-in": "Sign In",
    "qualification":"Qualification",
    "Halls":"Halls",
    "Number":"Number",
    "Capacity":"Capacity",
    "Floor":"Floor",
    "Availability":"Availability",
    "Not Available":"Not Available",
    "Available":"Available",
    "Reserve":"Reserve",
    "ReserveHall":"Reserve Hall",
    "confirm":"Confirm",
    "fromDate":"From Date",
    "toDate":"To Date",
    "Accepted":"Accepted",
    "Refused":"Refused",
    "default":"default",
    "rating":"rating",
    "There are no reviews":"There are no reviews",
    "No comments":"No comments",
    "comment":"Comment",
    "Last Name of Company Contact":"Last Name of Company Contact",
    "Company Contact Email Address":"Company Contact Email Address",
    "First Name of Company Contact":"First Name of Company Contact",
    "Company Phone Number":"Company Phone Number",
    "Company Website":"Company Website",
    "Company Mobile Phone":"Company Mobile Phone",
    "Street address for registered business":"Street address for registered business",
    "Apt / Suite":"Apt / Suite",
    "Continue":"Continue",
    "Post town":"Post town",
    "Postal Code":"Postal Code",
    "Next":"Next",
    "Office Phone":"Office Phone",
    "Add new Adress":"Add new Adress",
    "alladdress":"Address",
    "Adress name":"Adress name",
    "streetAddress":"Street Address",
    "Prev":"Prev",
    "Fill out the additional information":"Fill out the additional information",
    "Information of the person responsible for the company":"Information of the person responsible for the company",
    "Company Billing Information":"Company Billing Information",
    "The name of the person responsible for the company in Arabic":"The name of the person responsible for the company in Arabic",
    "First Name of Billing Contact":"First Name of Billing Contact",
    "Phone number of the person in charge of the company":"Phone number of the person in charge of the company",
    "Email of the person responsible for the company":"Email of the person responsible for the company",
    "Name of the person responsible for the company":"Name of the person responsible for the company",
    "Last Name of Billing Contact":"Last Name of Billing Contact",
    "Billing Email Address":"Billing Email Address",
    "Billing Phone Number":"Billing Phone Number",
    "Upload resale certificate, business certificate in which you are registered and/or will be conducting business.":"Upload resale certificate, business certificate in which you are registered and/or will be conducting business.",
    "upload your completed resale certificate in which you are likely to ship.":"upload your completed resale certificate in which you are likely to ship.",
    "Tax Exemption and Business Certificate Enrollment":"Tax Exemption and Business Certificate Enrollment",
    "Are you registered as a reseller for sales tax purposes or have a business certificate?":"Are you registered as a reseller for sales tax purposes or have a business certificate?",
    "Any additional information you would like to share with us?":"Any additional information you would like to share with us?",
    "How did you learn about MARBYA CHARM?":"How did you learn about MARBYA CHARM?",
    "What areas of interest would you like to hear about?":"What areas of interest would you like to hear about?",
    "Yes":"Yes",
    "No":"No",
    "Would you like to receive product updates, inspiration, news, and special offers from MARBYA CHARM?":"Would you like to receive product updates, inspiration, news, and special offers from MARBYA CHARM?",
    "Enter Your Email Adress":"Enter Your Email Adress",
    "StreetAddress2":"Street Address 2",
    "StreetAddress1":"Street Address 1",
    "firstname":"First Name",
    "lastname":"Last Name",
    "glamorousdes":"Enter the realm of bespoke luxury at our Glamorous Boutique, where sophistication meets customization. Explore our curated selection of exclusive items, meticulously crafted from premium materials to embody timeless elegance.Preorder your desired piece to embark on a journey of personalization, where every detail can be tailored to your exact specifications. Our attentive team is here to guide you through the process, ensuring that your vision is brought to life with unparalleled craftsmanship and attention to detail. Elevate your style with a touch of opulence that is uniquely yours.",
    "fullName":"Full Name",
    "Edit-Profile":"Edit Profile",
    "City":"City",
    "additional information":"Additional Information",
    "Please fill out the following fields":"Please fill out the following fields or",
    "Skip":"Skip",
    "companyNumber":"Company Number ",
    "companyWebsite":"Company Website",
    "companyName":"Company Name",
    "nameAr": "Arabic Name",
    "nameEn": "English Name",
    "responsiblePersonNameAr": "Responsible Person Name",
    "responsiblePersonNameEn": "Responsible Person Name in English",
    "responsiblePersonNamePhon": "Responsible Person Phone",
    "Your Name":"Your Name",
    "loading":"Loading",
    "unpaid":"Unpaid",
    "paid":"Paid",
    "newarrivaledesc":"Design your living masterpiece with our curated collection, because your home is the canvas of your life, and every piece tells a story of timeless elegancy",
    "personal": "personal",
    "person": "Person",
    "comapny": "Comapny",
    "ProjectsStables": "Projects Stables",
    "full-name": "Full Name",
    "full-name-ar": "Arabic Full Name",
    "company-name": "Company Name",
    "details": "Details",
    "select-country": "Select Country",
    "submit": "Submit",
    "or": "Or",
    "basket": "Basket",
    "Disclaimer_responsibility": "Disclaimer responsibility",
    "more-inforamtion": "More Inforamtion",
    "commercial-license-num": "Commercial License Number",
    "commercial-license-date": "Commercial License Date",
    "General_questions": "General questions",
    "Your search results For": "Your search results For",
    "search_by_name": "Search for the Product name",
    "Orders": "Orders",
    "Show_Detail": "Show Detail",
    "Photogallery": "Photo Gallery",
    "Cart-Totals": "Cart-Totals",
    "Bills": "Invoices",
    "Select City": "Select City",
    "Select Country": "Select Country",
    "Favorite": "Favorite",
    "Cart": "Cart",
    "Welcome to our extraordinary world of furniture where design meets functionaly and craftsmanship meets innovation": "Welcome to our extraordinary world of furniture where design meets functionaly and craftsmanship meets innovation",
    "furniture": "furniture",
    "Latest News, Events, and Offers": "Latest News, Events, and Offers",
    "Subsicribe": "Subsicribe",
    "Ener Email Address": "Ener Email Address"
    }
});